### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by tong-xz** [lucaxchen/lucaxchen#1]
Dear Lucas,

We are pleased to extend an offer to you for the position of Software Engineer at [Your Company Name]. We were impressed with your qualifications and experience, and we believe that you will be a valuable asset to our team.

Position: Software Engineer

Start Date:  January 1, 2024

Base Salary: $800,000 annually, payable in monthly instalments by direct deposit.

Work Schedule: Monday to Friday, 9:00 AM to 5:00 PM, with flexibility as required by project needs.

Reporting To: Xiangzhi Tong

Benefits:

Health, dental, and vision insurance after 60 days of employment
401(k) retirement plan with company match after one year of service
Paid time off (PTO) of 15 days annually
Company-sponsored professional development and training opportunities
Other Perks:

Remote work flexibility
Annual bonuses based on performance
Access to company software and tools
Please review the attached employment agreement and non-disclosure agreement for more details on the terms and conditions of your employment.

To accept this offer: You can no nothing.

If you have any questions or need further clarification on any aspect of this offer, please do not hesitate to contact us at xxxx.

We are excited about the potential of having you on our team and look forward to your positive response.

Warm regards,
Xiangzhi Tong

**Comment by lucaxchen** [comment]
Thx a lot!
